### PR TITLE
Enforce order of callback execution

### PR DESCRIPTION
**Pull request by arcusfelis**
Execute hooks inside wsecli process

Related esl/escalus#115

### CODE REVIEW

**Comment by fenek** [comment]
Why do you need these executed synchronously?

**Comment by arcusfelis** [comment]
@fenek because we have parsing errors when XML stanzas are delivered in wrong order. Like the infamous "unbound prefix" error. Also, some stanzas can be delivered like this:

```xml
<this_is_stan<this_is_stanza_two/>za_one/>
```

instead of 

```xml
<this_is_stanza_one/><this_is_stanza_two/>
```

**Comment by fenek** [comment]
Fair enough. :) It would be nice though to have extra test cases which verify that hooks do work. :) Do you think it would take long to add them?

**Comment by arcusfelis** [comment]
From tests:

```erlang
%% send_data is unfinished and fails. 
```

I guess it will take a lot of time to add tests, because there are almost none currently.

**Comment by fenek** [comment]
Manual test with `ejabberd_tests` passed so it's enough for me. :)

**Pull request merged**
